name: Setting environment variables for all jobs
on:
  workflow_call:
    inputs:
      dummy:
        required: false
        type: string
        default: ''

jobs:
  set-env-variables:
    name: Set environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Setup python 
        uses: actions/setup-python@v1
      - name: Install requirements 
        run: |
          pip install -r requirements.txt