name: 'All env vars'
description: 'Extract all common steps in a single file'

runs:
  using: "composite"
  steps:
    - name: Here we come
      run: |
        echo "Hello world!"

    - name: Setup python 
      uses: actions/setup-python@v1

    - name: Install requirements 
      run: |
        pip install -r requirements.txt