wiki_page:
  page_id: 111111
  page_title: "DTE - Jira Feature Work"
  show_approval_status: false
  sections:
    - name: "General overview of supported new features"
      reports:
        - report-title: "Total Features Supported"
          report-description: ""
          attachment-filename: "total-features-supported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "High-priority Features [High or Highest]"
          report-description: ""
          attachment-filename: "high-priority-features.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "Features that missed Manual QA Request milestone"
          report-description: ""
          attachment-filename: "features-missed-manual-qa-request-milestone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "Features that missed the tech documentation milestone"
          report-description: ""
          attachment-filename: "features-missed-tech-documentation-mileston.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "Features that missed the ready for QA milestone"
          report-description: ""
          attachment-filename: "features-missed-ready-qa-milestone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "Features that got their target release deferred"
          report-description: ""
          attachment-filename: "features-target-release-deferred.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"


    - name: "Effort based on feature size, complexity, and testing phase"
      reports:
        - report-title: "Size-based breakdown"
          report-description: ""
          attachment-filename: "size-based-breakdown.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "Complexity-based breakdown"
          report-description: ""
          attachment-filename: "complexity-based-breakdown.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"

        - report-title: "Total features tested all the way through Beta/Release"
          report-description: ""
          attachment-filename: "total-features-tested-all-the-way-beta-release.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"




