wiki_page:
  page_id: "1436811681"
  page_title: "Test Data Insights"
  sections:
    - name: "UI Test Data Insights - Android"
      reports:
        - report-title: "Fenix UI Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "fenix-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2815"
        - report-title: "Focus UI Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "focus-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2822"
        - report-title: "Fenix UI Test Flaky Rate KPI (Current Month Average)"
          report-description: "The average percentage of flaky tests in the last 30 days."
          attachment-filename: "fenix-ui-test-flaky-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2831"
        - report-title: "Focus UI Test Flaky Rate KPI (Current Month Average)"
          report-description: "The average percentage of flaky tests in the last 30 days."
          attachment-filename: "focus-flaky-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2833"
        - report-title: "Fenix UI Test Failure Rate KPI (Current Month Average)"
          report-description: "The average percentage of failed tests in the last 30 days."
          attachment-filename: "fenix-ui-test-failure-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2818"
        - report-title: "Focus UI Test Failure Rate KPI (Current Month Average)"
          report-description: "The average percentage of failed tests in the last 30 days."
          attachment-filename: "focus-failure-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2820"
        - report-title: "Fenix UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fenix-ui-test-flaky-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2835"
        - report-title: "Focus UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "focus-ui-test-flaky-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2839"
        - report-title: "Fenix UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fenix-ui-test-failure-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2837"
        - report-title: "Focus UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "focus-ui-test-failure-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2841"
        - report-title: "Fenix UI Test Flaky Rate by Month"
          report-description: "The percentage of flaky tests by month."
          attachment-filename: "fenix-ui-test-flaky-rate-by-month.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2869"
        - report-title: "Fenix UI Test Failure Rate by Month"
          report-description: "The percentage of failed tests by month."
          attachment-filename: "fenix-ui-test-failure-rate-by-month.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2871"
        - report-title: "Fenix UI Test Monthly Run Volume of UI Tests"
          report-description: "The number of tests run by month across all jobs."
          attachment-filename: "fenix-ui-test-monthly-run-volume.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2891"
        - report-title: "Focus UI Test Monthly Run Volume of UI Tests"
          report-description: "The number of tests run by month across all jobs."
          attachment-filename: "focus-ui-test-monthly-run-volume.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2893"

    - name: "UI Test Data Insights - iOS"
      reports:
        - report-title: "Fennec UI Flaky Tests Trend"
          report-description: "Firefox iOS UI Flaky Tests Trend in 2025"
          attachment-filename: "fennec-number-of-flaky-tests-trend.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2888"

        - report-title: "Fennec UI Failure Tests Trend"
          report-description: "Firefox iOS UI Failure Tests Trend in 2025"
          attachment-filename: "fennec-number-of-failure-tests-trend.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2889"

        - report-title: "Fennec Firefox iOS - Flaky Rate By Day"
          report-description: "Fennec Firefox iOS - Flaky Rate By Day 2025"
          attachment-filename: "fennec-ui-tests-flaky-rate-by-day-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2851"
          
        - report-title: "Fennec Firefox iOS - Failure Rate By Day"
          report-description: "Fennec Firefox iOS - Failure Rate By Day 2025"
          attachment-filename: "fennec-firefox-ios-failure-rate-by-day-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2852"

        - report-title: "Fennec Firefox iOS Daily Run Volume of UI Tests All Jobs - iPhone"
          report-description: "Fennec Firefox iOS Daily Run Volume of UI Tests All Jobs - iPhone"
          attachment-filename: "fennec-firefox-ios-daily-run-volume-of-ui-tests-all-jobs-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2855"

        - report-title: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPhone"
          report-description: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPhone"
          attachment-filename: "fennec-firefox-ios-monthly-run-volume-of-ui-tests-all-jobs-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2857"

        - report-title: "Fennec Firefox iOS - Flaky Rate By Day"
          report-description: "Fennec Firefox iOS - Flaky Rate By Day 2025"
          attachment-filename: "fennec-ui-tests-flaky-rate-by-day-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2853"
          
        - report-title: "Fennec Firefox iOS - Failure Rate By Day"
          report-description: "Fennec Firefox iOS - Failure Rate By Day 2025"
          attachment-filename: "fennec-ui-tests-failure-rate-by-day-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2854"

        - report-title: "Fennec Firefox iOS Daily Run Volume of UI Tests All Jobs - iPad"
          report-description: "Fennec Firefox iOS Daily Run Volume of UI Tests All Jobs - iPad"
          attachment-filename: "fennec-firefox-ios-daily-run-volume-of-ui-tests-all-jobs-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2856"

        - report-title: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPad"
          report-description: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPad"
          attachment-filename: "fennec-firefox-ios-monthly-run-volume-of-ui-tests-all-jobs-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2858"

        - report-title: "Fennec Monthly Run Volume of UI Tests"
          report-description: "Firefox iOS Monthly Run Volume of UI Tests"
          attachment-filename: "fennec-firefox-ios-monthly-run-volume-of-ui-tests.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2872"
      
        - report-title: "Fennec Firefox iOS Failure Rate By Month of UI Tests"
          report-description: "Firefox iOS Failure Rate By Month of UI Tests"
          attachment-filename: "fennec-firefox-ios-failure-rate-by-month-of-ui-tests.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2873"
