wiki_page:
  page_id: "1436811681"
  page_title: "Test Data Insights"
  sections:
    - name: "UI Test Data Insights - Android"
      reports:
        - report-title: "Fenix UI Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "fenix-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2815"
        - report-title: "Focus UI Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "focus-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2822"
        - report-title: "Fenix UI Test Flaky Rate KPI (Current Month Average)"
          report-description: "The average percentage of flaky tests in the last 30 days."
          attachment-filename: "fenix-ui-test-flaky-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2831"
        - report-title: "Focus UI Test Flaky Rate KPI (Current Month Average)"
          report-description: "The average percentage of flaky tests in the last 30 days."
          attachment-filename: "focus-flaky-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2833"
        - report-title: "Fenix UI Test Failure Rate KPI (Current Month Average)"
          report-description: "The average percentage of failed tests in the last 30 days."
          attachment-filename: "fenix-ui-test-failure-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2818"
        - report-title: "Focus UI Test Failure Rate KPI (Current Month Average)"
          report-description: "The average percentage of failed tests in the last 30 days."
          attachment-filename: "focus-failure-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2820"
        - report-title: "Fenix UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fenix-ui-test-flaky-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2835"
        - report-title: "Focus UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "focus-ui-test-flaky-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2839"
        - report-title: "Fenix UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fenix-ui-test-failure-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2837"
        - report-title: "Focus UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "focus-ui-test-failure-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2841"
