wiki_page:
  page_id: "1668087814"
  page_title: "Desktop Bugzilla Insights"
  sections:
    - name: "All Bugs per Release"
      reports:
        - report-title: "Number of Bugs per Release"
          report-description: "Count number of bugs found per release QA Whiteboard qa-found-in-<b/cversion>"
          attachment-filename: "number-of-bugs-per-release.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2983"
    
    - name: "Release 140"
      reports:
        - report-title: "Regressions"
          report-description: "Number of regressions found - Keywords: regression"
          attachment-filename: "140-regressions.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2975"
        - report-title: "S1/S2"
          report-description: "Number of bugs with severity S1 and S2"
          attachment-filename: "140-severity-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2976"
        - report-title: "S1/S2 %"
          report-description: "% of bugs with severity S1 and S2"
          attachment-filename: "140-s1-s2-percentage.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2978"
        - report-title: "Bugs by severity"
          report-description: "Number of bugs by severity"
          attachment-filename: "140-bugs-by-severity.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2979"
        - report-title: "Papercut bugs"
          report-description: "Papercut bugs - Whiteboard: [fidefe-quality-foundation?] "
          attachment-filename: "140-papercuts.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2977"
        - report-title: "Average time to fix a bug"
          report-description: "Average time to fix a bug (days)"
          attachment-filename: "140-average-time-to-fix-days.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2980"

    - name: "Release 141"
      reports:
        - report-title: "Regressions"
          report-description: "Regressions found"
          attachment-filename: "141-regressions.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/"