name: Testops Confluence Update

# Daily @2am UTC
on:
  schedule:
    - cron:  "0 2 * * *"
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Default branch'
        required: true
        default: 'master'

jobs:
  deploy:
    name: TestOps Confluence Update (DAILY) 
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v1

      - name: Install requirements 
        run: pip install -r requirements.txt

      - name: Set env vars 
        run: |
            echo "ATLASSIAN_API_TOKEN=${{ secrets.ATLASSIAN_API_TOKEN }}" >> $GITHUB_ENV
            echo "ATLASSIAN_HOST=${{ secrets.ATLASSIAN_HOST }}" >> $GITHUB_ENV
            echo "ATLASSIAN_USERNAME=${{ secrets.ATLASSIAN_USERNAME }}" >> $GITHUB_ENV
            echo "LOOKER_HOST=${{ secrets.LOOKER_HOST }}" >> $GITHUB_ENV
            echo "LOOKER_CLIENT_ID=${{ secrets.LOOKER_CLIENT_ID }}" >> $GITHUB_ENV
            echo "LOOKER_SECRET=${{ secrets.LOOKER_SECRET }}" >> $GITHUB_ENV

      - name: Generate Looker Thumbnails
        run: |
            python3 ./looker.py
            ls
            ls confluence/images/

      - name: Update Confluence Page
        run: python3 ./api_confluence.py
