name: Testops Report PUSH 

on:
  push:
    branches:
      - master 
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Default branch'
        required: true
        default: 'master'

jobs:
  deploy:
    name: TestOps Report (PUSH)
    uses: ./.github/workflows/all-jobs.yml
    with:
      database: 'staging'
    secrets: inherit